spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: auth-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: category-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/categories/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
      discovery:
        locator:
          enabled: true
server:
  port: 8222
management:
  tracing:
    sampling:
      probability: 1.0
