spring:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/user/*
      discovery:
        locator:
          enabled: true
server:
  port: 8222
manage:
  tracing:
    sampling:
      probability: 1.0