eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
spring:
  data:
    mongodb:
      username: nourhan
      password: password
      host: localhost
      port: 27017
      database: notifications
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-server: localhost:9092
      group-id: notification-group
  mail:
    host: smtp.example.com
    port: 587
    username: wtest1284@gmail.com
    password: lhzw tjtx qwlk chee
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true

server:
  port: 8042
