spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092  # Kafka broker address (change to match your Kafka broker)
    properties:
      spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
      spring.kafka.producer.value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: 8080
management:
  tracing:
    sampling:
      probability: 1.0
application:
  config:
    product-url: http://localhost:8222/api/v1/products
    user-service-url: http://localhost:8222/api/v1/users
