eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://#{eureka.instance.hostname}/8761/eureka
  spring:
    database:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/products
      username: postgres
      password: password
    jpa:
      hibernate:
        ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8060
management:
  tracing:
    sampling:
      probability: 1.0